package com.pushkar.codereview.github.review.rule;

import com.pushkar.codereview.github.review.dto.FindingSource;
import com.pushkar.codereview.github.review.dto.ReviewFinding;
import com.pushkar.codereview.github.review.dto.ReviewFindingCategory;
import com.pushkar.codereview.github.review.dto.ReviewFindingSeverity;

import java.util.Objects;

/**
 * Represents a single finding generated by a deterministic CodeQualityRule.
 */
public class RuleFinding {

    private final String ruleId;
    private final String filename;
    private final Integer line;
    private final Integer endLine;
    private final ReviewFindingSeverity severity;
    private final ReviewFindingCategory category;
    private final String message;
    private final String suggestion;

    public RuleFinding(String ruleId, String filename, Integer line, Integer endLine,
                       ReviewFindingSeverity severity, ReviewFindingCategory category,
                       String message, String suggestion) {
        this.ruleId = ruleId != null ? ruleId : "UNKNOWN_RULE";
        this.filename = filename != null ? filename : "";
        this.line = line != null ? line : 1;
        this.endLine = endLine != null ? endLine : this.line;
        this.severity = severity != null ? severity : ReviewFindingSeverity.INFO;
        this.category = category != null ? category : ReviewFindingCategory.OTHER;
        this.message = message != null ? message : "";
        this.suggestion = suggestion;
    }

    public String getRuleId() {
        return ruleId;
    }

    public String getFilename() {
        return filename;
    }

    public Integer getLine() {
        return line;
    }

    public Integer getEndLine() {
        return endLine;
    }

    public ReviewFindingSeverity getSeverity() {
        return severity;
    }

    public ReviewFindingCategory getCategory() {
        return category;
    }

    public String getMessage() {
        return message;
    }

    public String getSuggestion() {
        return suggestion;
    }

    /**
     * Converts this rule finding into a standard ReviewFinding domain object for downstream persistence and comments.
     */
    public ReviewFinding toReviewFinding() {
        return new ReviewFinding(
                filename,
                line,
                severity,
                category,
                message,
                suggestion,
                FindingSource.RULE
        );
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        RuleFinding that = (RuleFinding) o;
        return Objects.equals(ruleId, that.ruleId) &&
                Objects.equals(filename, that.filename) &&
                Objects.equals(line, that.line) &&
                Objects.equals(endLine, that.endLine) &&
                severity == that.severity &&
                category == that.category &&
                Objects.equals(message, that.message) &&
                Objects.equals(suggestion, that.suggestion);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ruleId, filename, line, endLine, severity, category, message, suggestion);
    }

    @Override
    public String toString() {
        return "RuleFinding{" +
                "ruleId='" + ruleId + '\'' +
                ", filename='" + filename + '\'' +
                ", line=" + line +
                ", endLine=" + endLine +
                ", severity=" + severity +
                ", category=" + category +
                ", message='" + message + '\'' +
                '}';
    }
}
