package com.pushkar.codereview.config;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

@Component
public class CodeReviewMetrics {

    private final MeterRegistry meterRegistry;
    private final Counter submissionsCounter;
    private final Counter duplicateSubmissionsCounter;
    private final Counter completedCounter;
    private final Counter failedCounter;
    private final Counter findingsCounter;
    private final Counter commentsCounter;
    private final Counter githubFailuresCounter;
    private final Timer executionTimer;
    private final Timer aiExecutionTimer;
    private final AtomicInteger inProgressGauge;

    public CodeReviewMetrics(@Autowired(required = false) MeterRegistry meterRegistry) {
        this.meterRegistry = (meterRegistry != null) ? meterRegistry : new SimpleMeterRegistry();

        this.submissionsCounter = Counter.builder("code_review.submissions.total")
                .tag("type", "new")
                .description("Total number of code review requests submitted")
                .register(this.meterRegistry);

        this.duplicateSubmissionsCounter = Counter.builder("code_review.submissions.total")
                .tag("type", "duplicate")
                .description("Total number of duplicate code review requests submitted")
                .register(this.meterRegistry);

        this.completedCounter = Counter.builder("code_review.completed.total")
                .description("Total number of code reviews completed successfully")
                .register(this.meterRegistry);

        this.failedCounter = Counter.builder("code_review.failed.total")
                .description("Total number of code reviews that failed during execution")
                .register(this.meterRegistry);

        this.findingsCounter = Counter.builder("code_review.findings.total")
                .description("Total number of review findings generated by AI")
                .register(this.meterRegistry);

        this.commentsCounter = Counter.builder("code_review.comments.total")
                .description("Total number of review comments posted to GitHub")
                .register(this.meterRegistry);

        this.githubFailuresCounter = Counter.builder("code_review.github.failures")
                .description("Total number of GitHub API or comment posting failures")
                .register(this.meterRegistry);

        this.executionTimer = Timer.builder("code_review.execution.time")
                .description("Duration of asynchronous code review executions")
                .register(this.meterRegistry);

        this.aiExecutionTimer = Timer.builder("code_review.ai.execution.time")
                .description("Duration of AI review model inference execution")
                .register(this.meterRegistry);

        this.inProgressGauge = this.meterRegistry.gauge("code_review.in_progress",
                new AtomicInteger(0));
    }

    public void recordSubmission(boolean isDuplicate) {
        if (isDuplicate) {
            duplicateSubmissionsCounter.increment();
        } else {
            submissionsCounter.increment();
        }
    }

    public void recordCompleted() {
        completedCounter.increment();
    }

    public void recordFailed() {
        failedCounter.increment();
    }

    public void recordExecutionTime(long durationMillis) {
        executionTimer.record(durationMillis, TimeUnit.MILLISECONDS);
    }

    public void recordAiExecutionTime(long durationMillis) {
        aiExecutionTimer.record(durationMillis, TimeUnit.MILLISECONDS);
    }

    public void recordGithubFailure() {
        githubFailuresCounter.increment();
    }

    public void recordFindings(int count) {
        if (count > 0) {
            findingsCounter.increment(count);
        }
    }

    public void recordCommentsPosted(int count) {
        if (count > 0) {
            commentsCounter.increment(count);
        }
    }

    public void incrementInProgress() {
        if (inProgressGauge != null) {
            inProgressGauge.incrementAndGet();
        }
    }

    public void decrementInProgress() {
        if (inProgressGauge != null && inProgressGauge.get() > 0) {
            inProgressGauge.decrementAndGet();
        }
    }

    public MeterRegistry getMeterRegistry() {
        return meterRegistry;
    }

    public Counter getSubmissionsCounter() {
        return submissionsCounter;
    }

    public Counter getDuplicateSubmissionsCounter() {
        return duplicateSubmissionsCounter;
    }

    public Counter getCompletedCounter() {
        return completedCounter;
    }

    public Counter getFailedCounter() {
        return failedCounter;
    }

    public Counter getFindingsCounter() {
        return findingsCounter;
    }

    public Counter getCommentsCounter() {
        return commentsCounter;
    }

    public Counter getGithubFailuresCounter() {
        return githubFailuresCounter;
    }

    public Timer getExecutionTimer() {
        return executionTimer;
    }

    public Timer getAiExecutionTimer() {
        return aiExecutionTimer;
    }

    public int getInProgressCount() {
        return inProgressGauge != null ? inProgressGauge.get() : 0;
    }
}
