package com.pushkar.codereview.config;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

@Component
public class CodeReviewMetrics {

    private final MeterRegistry meterRegistry;

    // Business Counters & Timers
    private final Counter submissionsCounter;
    private final Counter submissionSingularCounter;
    private final Counter duplicateSubmissionsCounter;
    private final Counter completedCounter;
    private final Counter failedCounter;
    private final Counter findingsCounter;
    private final Counter commentsCounter;
    private final Counter commentsPostedCounter;
    private final Counter githubFailuresCounter;
    private final Timer executionTimer;
    private final Timer durationTimer;
    private final Timer aiExecutionTimer;
    private final AtomicInteger inProgressGauge;

    // Resilience & External Dependency Metrics Maps
    private final Map<String, Counter> retryCounters = new ConcurrentHashMap<>();
    private final Map<String, Counter> circuitBreakerOpenCounters = new ConcurrentHashMap<>();
    private final Map<String, Counter> externalFailureCounters = new ConcurrentHashMap<>();

    private final Map<String, Counter> apiRequestSuccessCounters = new ConcurrentHashMap<>();
    private final Map<String, Counter> apiRequestFailedCounters = new ConcurrentHashMap<>();
    private final Map<String, Counter> apiFailureCounters = new ConcurrentHashMap<>();
    private final Map<String, Timer> apiDurationTimers = new ConcurrentHashMap<>();

    public CodeReviewMetrics(@Autowired(required = false) MeterRegistry meterRegistry) {
        this.meterRegistry = (meterRegistry != null) ? meterRegistry : new SimpleMeterRegistry();

        this.submissionsCounter = Counter.builder("code_review.submissions.total")
                .tag("type", "new")
                .description("Total number of code review requests submitted")
                .register(this.meterRegistry);

        this.submissionSingularCounter = Counter.builder("code_review.submission.total")
                .tag("type", "new")
                .description("Total number of code review requests submitted")
                .register(this.meterRegistry);

        this.duplicateSubmissionsCounter = Counter.builder("code_review.submissions.total")
                .tag("type", "duplicate")
                .description("Total number of duplicate code review requests submitted")
                .register(this.meterRegistry);

        this.completedCounter = Counter.builder("code_review.completed.total")
                .description("Total number of code reviews completed successfully")
                .register(this.meterRegistry);

        this.failedCounter = Counter.builder("code_review.failed.total")
                .description("Total number of code reviews that failed during execution")
                .register(this.meterRegistry);

        this.findingsCounter = Counter.builder("code_review.findings.total")
                .description("Total number of review findings generated by AI")
                .register(this.meterRegistry);

        this.commentsCounter = Counter.builder("code_review.comments.total")
                .description("Total number of review comments posted to GitHub")
                .register(this.meterRegistry);

        this.commentsPostedCounter = Counter.builder("code_review.comments.posted.total")
                .description("Total number of review comments posted to GitHub")
                .register(this.meterRegistry);

        this.githubFailuresCounter = Counter.builder("code_review.github.failures")
                .description("Total number of GitHub API or comment posting failures")
                .register(this.meterRegistry);

        this.executionTimer = Timer.builder("code_review.execution.time")
                .description("Duration of asynchronous code review executions")
                .register(this.meterRegistry);

        this.durationTimer = Timer.builder("code_review.duration")
                .description("Duration of asynchronous code review executions")
                .register(this.meterRegistry);

        this.aiExecutionTimer = Timer.builder("code_review.ai.execution.time")
                .description("Duration of AI review model inference execution")
                .register(this.meterRegistry);

        this.inProgressGauge = this.meterRegistry.gauge("code_review.in_progress",
                new AtomicInteger(0));
    }

    public void recordSubmission(boolean isDuplicate) {
        if (isDuplicate) {
            duplicateSubmissionsCounter.increment();
        } else {
            submissionsCounter.increment();
            submissionSingularCounter.increment();
        }
    }

    public void recordCompleted() {
        completedCounter.increment();
    }

    public void recordFailed() {
        failedCounter.increment();
    }

    public void recordExecutionTime(long durationMillis) {
        executionTimer.record(durationMillis, TimeUnit.MILLISECONDS);
        durationTimer.record(durationMillis, TimeUnit.MILLISECONDS);
    }

    public void recordAiExecutionTime(long durationMillis) {
        aiExecutionTimer.record(durationMillis, TimeUnit.MILLISECONDS);
        recordExternalApiRequest("gemini", true, durationMillis);
    }

    public void recordGithubFailure() {
        githubFailuresCounter.increment();
        recordExternalApiFailure("github");
    }

    public void recordRetry(String dependency) {
        String dep = (dependency != null && !dependency.isBlank()) ? dependency.toLowerCase() : "unknown";
        retryCounters.computeIfAbsent(dep, k -> Counter.builder("code_review.retry.total")
                .tag("dependency", k)
                .description("Total number of retry attempts for external operations")
                .register(meterRegistry)).increment();
    }

    public void recordCircuitBreakerOpen(String dependency) {
        String dep = (dependency != null && !dependency.isBlank()) ? dependency.toLowerCase() : "unknown";
        circuitBreakerOpenCounters.computeIfAbsent(dep, k -> Counter.builder("code_review.circuit_breaker.open.total")
                .tag("dependency", k)
                .description("Total number of requests rejected due to an open circuit breaker")
                .register(meterRegistry)).increment();
    }

    public void recordExternalFailure(String dependency) {
        String dep = (dependency != null && !dependency.isBlank()) ? dependency.toLowerCase() : "unknown";
        externalFailureCounters.computeIfAbsent(dep, k -> Counter.builder("code_review.external_failure.total")
                .tag("dependency", k)
                .description("Total number of external dependency failures after retries")
                .register(meterRegistry)).increment();
    }

    public void recordExternalApiRequest(String dependency, boolean success, long durationMillis) {
        String dep = (dependency != null && !dependency.isBlank()) ? dependency.toLowerCase() : "unknown";
        String metricPrefix = dep.equals("github") ? "github.api" : (dep.equals("gemini") ? "gemini.api" : dep + ".api");

        if (success) {
            apiRequestSuccessCounters.computeIfAbsent(dep, k -> Counter.builder(metricPrefix + ".request")
                    .tag("dependency", k)
                    .tag("status", "success")
                    .description("Total successful API requests to external dependency")
                    .register(meterRegistry)).increment();
        } else {
            apiRequestFailedCounters.computeIfAbsent(dep, k -> Counter.builder(metricPrefix + ".request")
                    .tag("dependency", k)
                    .tag("status", "failed")
                    .description("Total failed API requests to external dependency")
                    .register(meterRegistry)).increment();

            recordExternalApiFailure(dep);
        }

        apiDurationTimers.computeIfAbsent(dep, k -> Timer.builder(metricPrefix + ".duration")
                .tag("dependency", k)
                .description("Duration of API requests to external dependency")
                .register(meterRegistry)).record(durationMillis, TimeUnit.MILLISECONDS);
    }

    public void recordExternalApiFailure(String dependency) {
        String dep = (dependency != null && !dependency.isBlank()) ? dependency.toLowerCase() : "unknown";
        String metricPrefix = dep.equals("github") ? "github.api" : (dep.equals("gemini") ? "gemini.api" : dep + ".api");

        apiFailureCounters.computeIfAbsent(dep, k -> Counter.builder(metricPrefix + ".failure")
                .tag("dependency", k)
                .description("Total API request failures for external dependency")
                .register(meterRegistry)).increment();
    }

    public void recordFindings(int count) {
        if (count > 0) {
            findingsCounter.increment(count);
        }
    }

    public void recordCommentsPosted(int count) {
        if (count > 0) {
            commentsCounter.increment(count);
            commentsPostedCounter.increment(count);
        }
    }

    public void incrementInProgress() {
        if (inProgressGauge != null) {
            inProgressGauge.incrementAndGet();
        }
    }

    public void decrementInProgress() {
        if (inProgressGauge != null && inProgressGauge.get() > 0) {
            inProgressGauge.decrementAndGet();
        }
    }

    public MeterRegistry getMeterRegistry() {
        return meterRegistry;
    }

    public Counter getSubmissionsCounter() {
        return submissionsCounter;
    }

    public Counter getSubmissionSingularCounter() {
        return submissionSingularCounter;
    }

    public Counter getDuplicateSubmissionsCounter() {
        return duplicateSubmissionsCounter;
    }

    public Counter getCompletedCounter() {
        return completedCounter;
    }

    public Counter getFailedCounter() {
        return failedCounter;
    }

    public Counter getFindingsCounter() {
        return findingsCounter;
    }

    public Counter getCommentsCounter() {
        return commentsCounter;
    }

    public Counter getCommentsPostedCounter() {
        return commentsPostedCounter;
    }

    public Counter getGithubFailuresCounter() {
        return githubFailuresCounter;
    }

    public Counter getRetryCounter(String dependency) {
        return retryCounters.get(dependency.toLowerCase());
    }

    public Counter getCircuitBreakerOpenCounter(String dependency) {
        return circuitBreakerOpenCounters.get(dependency.toLowerCase());
    }

    public Counter getExternalFailureCounter(String dependency) {
        return externalFailureCounters.get(dependency.toLowerCase());
    }

    public Timer getExecutionTimer() {
        return executionTimer;
    }

    public Timer getDurationTimer() {
        return durationTimer;
    }

    public Timer getAiExecutionTimer() {
        return aiExecutionTimer;
    }

    public int getInProgressCount() {
        return inProgressGauge != null ? inProgressGauge.get() : 0;
    }
}
