package com.pushkar.codereview.config;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.concurrent.TimeUnit;

@Component
public class CodeReviewMetrics {

    private final MeterRegistry meterRegistry;
    private final Counter submissionsCounter;
    private final Counter duplicateSubmissionsCounter;
    private final Counter completedCounter;
    private final Counter failedCounter;
    private final Counter findingsCounter;
    private final Counter commentsCounter;
    private final Timer executionTimer;

    public CodeReviewMetrics(@Autowired(required = false) MeterRegistry meterRegistry) {
        this.meterRegistry = (meterRegistry != null) ? meterRegistry : new SimpleMeterRegistry();

        this.submissionsCounter = Counter.builder("code_review.submissions.total")
                .tag("type", "new")
                .description("Total number of code review requests submitted")
                .register(this.meterRegistry);

        this.duplicateSubmissionsCounter = Counter.builder("code_review.submissions.total")
                .tag("type", "duplicate")
                .description("Total number of duplicate code review requests submitted")
                .register(this.meterRegistry);

        this.completedCounter = Counter.builder("code_review.completed.total")
                .description("Total number of code reviews completed successfully")
                .register(this.meterRegistry);

        this.failedCounter = Counter.builder("code_review.failed.total")
                .description("Total number of code reviews that failed during execution")
                .register(this.meterRegistry);

        this.findingsCounter = Counter.builder("code_review.findings.total")
                .description("Total number of review findings generated by AI")
                .register(this.meterRegistry);

        this.commentsCounter = Counter.builder("code_review.comments.total")
                .description("Total number of review comments posted to GitHub")
                .register(this.meterRegistry);

        this.executionTimer = Timer.builder("code_review.execution.time")
                .description("Duration of asynchronous code review executions")
                .register(this.meterRegistry);
    }

    public void recordSubmission(boolean isDuplicate) {
        if (isDuplicate) {
            duplicateSubmissionsCounter.increment();
        } else {
            submissionsCounter.increment();
        }
    }

    public void recordCompleted() {
        completedCounter.increment();
    }

    public void recordFailed() {
        failedCounter.increment();
    }

    public void recordExecutionTime(long durationMillis) {
        executionTimer.record(durationMillis, TimeUnit.MILLISECONDS);
    }

    public void recordFindings(int count) {
        if (count > 0) {
            findingsCounter.increment(count);
        }
    }

    public void recordCommentsPosted(int count) {
        if (count > 0) {
            commentsCounter.increment(count);
        }
    }

    public MeterRegistry getMeterRegistry() {
        return meterRegistry;
    }

    public Counter getSubmissionsCounter() {
        return submissionsCounter;
    }

    public Counter getDuplicateSubmissionsCounter() {
        return duplicateSubmissionsCounter;
    }

    public Counter getCompletedCounter() {
        return completedCounter;
    }

    public Counter getFailedCounter() {
        return failedCounter;
    }

    public Counter getFindingsCounter() {
        return findingsCounter;
    }

    public Counter getCommentsCounter() {
        return commentsCounter;
    }

    public Timer getExecutionTimer() {
        return executionTimer;
    }
}
